### ISSUE TITLE
about reference your paper

### ISSUE THREAD

**Issue by wenbeier** [csiro-robotics/locus#2]
Can you provide the page range of your paper. Sincerely thanks！

**Comment by peymmo** [comment]
Hi @wenbeier Unfortunately IEEE hasn't released the page number yet. Please Cite using this format; 
Kavisha Vidanapathirana, Peyman Moghadam, Ben Harwood, Muming Zhao, Sridha Sridharan, and Clinton Fookes. “Locus: LiDAR-based Place Recognition using Spatiotemporal Higher-Order Pooling.” IEEE International Conference on Robotics and Automation (ICRA), 2021.
