### ISSUE TITLE
About the variable 'vlad' in the file './evaluation/place_recognition.py'

### ISSUE THREAD

**Issue by shenhai911** [csiro-robotics/locus#6]
Hello, when I read your codes, I have some confusion about the variable 'vlad' at https://github.com/csiro-robotics/locus/blob/f16839f802e29f297c79fbe6f4d3b311969c89fc/evaluation/place_recognition.py#L92C9-L92C44

Can you provide the meaning or definition of this variable. Sincerely thanks！

**Comment by kavisha725** [comment]
Thanks for pointing this out. 'vlad' was an old variable name that I forgot to update when reformatting my code. I have fixed this in the latest commit: https://github.com/csiro-robotics/locus/blob/781c1ba340db4bad6ac2760fc8f1920998f56230/evaluation/place_recognition.py#L92

Please test it and let me know if you have more questions.

**Comment by kavisha725** [comment]
Closing the issue. Feel free to reopen if it's not resolved.

**Comment by shenhai911** [comment]
Thank you for your reply, the problem has been solved, but I have another question to consult. At https://github.com/csiro-robotics/locus/blob/781c1ba340db4bad6ac2760fc8f1920998f56230/evaluation/place_recognition.py#L36C1-L36C110
you use cosine distance to calculate the distance between two feature descriptors, and the threshold range is set to [0, 1.0]. I would like to consult, what would be the difference if Euclidean distance is used to calculate the distance between featrue descriptors? And what should the threshold range be set to in this case?

**Comment by shenhai911** [comment]
> Thanks for pointing this out. 'vlad' was an old variable name that I forgot to update when reformatting my code. I have fixed this in the latest commit:
> 
> https://github.com/csiro-robotics/locus/blob/781c1ba340db4bad6ac2760fc8f1920998f56230/evaluation/place_recognition.py#L92
> 
> Please test it and let me know if you have more questions.

Thank you for your reply, the problem has been solved, but I have another question to consult. At https://github.com/csiro-robotics/locus/blob/781c1ba340db4bad6ac2760fc8f1920998f56230/evaluation/place_recognition.py#L36C1-L36C110
you use cosine distance to calculate the distance between two feature descriptors, and the threshold range is set to [0, 1.0]. I would like to consult, what would be the difference if Euclidean distance is used to calculate the distance between featrue descriptors? And what should the threshold range be set to in this case?
